# fly.toml app configuration file generated for gophemeral-nameless-wind-7251 on 2023-11-29T17:59:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gophemeral-nameless-wind-7251"
primary_region = "iad"

[env]
  GOPHEMERAL_URLS="tls://connect.ngs.global"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
