# fly.toml app configuration file generated for gophemeral-nameless-wind-7251 on 2023-11-26T19:00:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gophemeral-nameless-wind-7251"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source="gophemeral_data"
  destination="/database"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
